defmodule GiTF.GitIdentityTest do
  @moduledoc """
  Ministry identity (docs/plans/ministry.md M1): `[git] author_name /
  author_email` become repo-local git config so every commit-maker —
  ghosts, consolidation, sync, publish — carries the ministry's identity.
  Unset = today's behaviour. `[git] attribution` governs the PR signature.
  """
  use GiTF.StoreCase

  alias GiTF.Config.Provider
  alias GiTF.Git
  alias GiTF.Signature

  setup do
    wt = Path.join(System.tmp_dir!(), "gitf_identity_#{:erlang.unique_integer([:positive])}")
    File.mkdir_p!(wt)
    {_, 0} = Git.safe_cmd(["init", "-b", "main"], cd: wt)

    # put_in needs the parent key; a bare test node may not have loaded the
    # [git] defaults. Seed an empty section and restore whatever was there.
    previous = Provider.get([:git])
    Provider.put([:git], %{})

    on_exit(fn ->
      Provider.put([:git], previous || %{})
      File.rm_rf(wt)
    end)

    %{wt: wt}
  end

  defp local_config(wt, key) do
    case Git.safe_cmd(["-C", wt, "config", "--local", "--get", key]) do
      {out, 0} -> String.trim(to_string(out))
      _ -> nil
    end
  end

  test "configured identity is written repo-local, and worktree commits carry it", %{wt: wt} do
    Provider.put([:git, :author_name], "Work Ghost")
    Provider.put([:git, :author_email], "matthew@trajectorservices.com")

    assert :ok = Git.ensure_identity(wt)
    assert local_config(wt, "user.name") == "Work Ghost"
    assert local_config(wt, "user.email") == "matthew@trajectorservices.com"

    File.write!(Path.join(wt, "a.txt"), "a")
    {_, 0} = Git.safe_cmd(["-C", wt, "add", "a.txt"])
    {_, 0} = Git.safe_cmd(["-C", wt, "commit", "-m", "work"])

    {log, 0} = Git.safe_cmd(["-C", wt, "log", "-1", "--format=%an <%ae>|%cn <%ce>"])

    assert String.trim(to_string(log)) ==
             "Work Ghost <matthew@trajectorservices.com>|Work Ghost <matthew@trajectorservices.com>"
  end

  test "ensure_identity is idempotent", %{wt: wt} do
    Provider.put([:git, :author_name], "Work Ghost")
    Provider.put([:git, :author_email], "w@example.com")
    assert :ok = Git.ensure_identity(wt)
    assert :ok = Git.ensure_identity(wt)
    assert local_config(wt, "user.email") == "w@example.com"
  end

  test "unset identity is a no-op — today's behaviour", %{wt: wt} do
    Provider.put([:git, :author_name], "")
    Provider.put([:git, :author_email], "")

    assert Git.identity() == nil
    assert :ok = Git.ensure_identity(wt)
    assert local_config(wt, "user.name") == nil
  end

  test "half an identity is no identity" do
    Provider.put([:git, :author_name], "Only Name")
    Provider.put([:git, :author_email], "")
    assert Git.identity() == nil
  end

  describe "attribution" do
    test "default: the Ghost in the Shell quote (today's behaviour)" do
      Provider.put([:git, :attribution], "")
      signed = Signature.sign("body")
      assert signed =~ "body\n\n---\n"
      assert signed =~ "Ghost in the Shell"
    end

    test "off: the text is untouched — client ministries" do
      Provider.put([:git, :attribution], "off")
      assert Signature.sign("body") == "body"
    end

    test "custom text becomes the signature block" do
      Provider.put([:git, :attribution], "Generated by the Trajector delivery factory.")
      signed = Signature.sign("body")
      assert signed =~ "Generated by the Trajector delivery factory."
      refute signed =~ "Ghost in the Shell"
    end
  end
end
